import Head from "next/head";
import React from "react";
import Header from "./Header";
import PageFooter from "./PageFooter";

const Layout: React.FC<{ children: JSX.Element }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Blossom Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-[88%] mx-auto">{children}</div>
      <PageFooter />
    </>
  );
};

export default Layout;
